# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - smart-mental-health-chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql

      - name: Install PHP dependencies
        run: composer validate --no-check-publish && composer install --no-dev --prefer-dist --no-progress --optimize-autoloader

      - name: Build frontend assets
        run: npm ci && npm run build

      - name: Prepare Laravel runtime folders
        run: |
          mkdir -p storage/framework/cache/data
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
          touch storage/framework/cache/data/.gitignore
          touch storage/framework/sessions/.gitignore
          touch storage/framework/views/.gitignore
          touch storage/logs/.gitignore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21064248CD9A426B8C758DF779A8A4EC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C2AB166C67B149608F9A1913BD931047 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9AED431AD064929BC9F78D599CACC79 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'smart-mental-health-chatbot'
          slot-name: 'Production'
          package: .
          
